import {
  Leaf,
  Droplet,
  Bug,
  Zap,
  Package,
  Utensils,
  Layers,
  Wind,
  Lightbulb,
  TrendingUp,
  Sprout,
  Wheat,
} from "lucide-react"

export type Product = {
  id: string
  name: string
  description: string
  category: string
  icon: any
  color: string
  url: string
}

export const products: Product[] = [
  {
    id: "quinoa-seeds-1",
    name: "Semilla Orgánica Quinua Roja",
    description: "Variedad certificada de quinua roja con alto contenido de proteína",
    category: "Semillas",
    icon: Leaf,
    color: "bg-red-50 text-red-600",
    url: "https://www.fao.org/quinoa",
  },
  {
    id: "quinoa-seeds-2",
    name: "Semilla Orgánica Quinua Blanca",
    description: "Semilla blanca adaptada al altiplano boliviano con excelente rendimiento",
    category: "Semillas",
    icon: Wheat,
    color: "bg-amber-50 text-amber-600",
    url: "https://www.fao.org/quinoa",
  },
  {
    id: "quinoa-seeds-3",
    name: "Semilla Orgánica Quinua Negra",
    description: "Variedad negra con propiedades antioxidantes superiores",
    category: "Semillas",
    icon: Leaf,
    color: "bg-slate-100 text-slate-700",
    url: "https://www.fao.org/quinoa",
  },
  {
    id: "biofertilizer-1",
    name: "Biofertilizante Microbiano",
    description: "Inoculante bioactivado para mejorar fertilidad de suelos del altiplano",
    category: "Bioinsumos",
    icon: Droplet,
    color: "bg-green-50 text-green-600",
    url: "https://www.fao.org/agriculture",
  },
  {
    id: "bioinsecticide-1",
    name: "Bioinsecticida Natural",
    description: "Control biológico de plagas sin químicos sintéticos",
    category: "Bioinsumos",
    icon: Bug,
    color: "bg-lime-50 text-lime-600",
    url: "https://www.fao.org/agriculture",
  },
  {
    id: "compost-1",
    name: "Compost Orgánico Premium",
    description: "Enmienda de suelos con materia orgánica procesada localmente",
    category: "Enmiendas",
    icon: Layers,
    color: "bg-orange-50 text-orange-600",
    url: "https://www.fao.org/agriculture",
  },
  {
    id: "mulch-1",
    name: "Mulch de Gramíneas Nativas",
    description: "Cobertura vegetal para retención de humedad en suelos áridos",
    category: "Enmiendas",
    icon: Wind,
    color: "bg-yellow-50 text-yellow-600",
    url: "https://www.fao.org/agriculture",
  },
  {
    id: "tool-1",
    name: "Kit de Herramientas Agrícolas",
    description: "Herramientas manuales adaptadas para cultivo de quinua",
    category: "Herramientas",
    icon: Zap,
    color: "bg-blue-50 text-blue-600",
    url: "https://www.fao.org/agriculture",
  },
  {
    id: "equipment-1",
    name: "Sistema de Riego por Goteo",
    description: "Infraestructura de riego eficiente para zonas de precipitación baja",
    category: "Equipos",
    icon: Droplet,
    color: "bg-cyan-50 text-cyan-600",
    url: "https://www.fao.org/agriculture",
  },
  {
    id: "fertilizer-1",
    name: "Abono Orgánico Certificado",
    description: "Fertilizante de origen animal con micronutrientes esenciales",
    category: "Fertilizantes",
    icon: Sprout,
    color: "bg-teal-50 text-teal-600",
    url: "https://www.fao.org/agriculture",
  },
  {
    id: "guide-1",
    name: "Guía de Buenas Prácticas Agrícolas",
    description: "Manual completo de cultivo sostenible de quinua en altiplano",
    category: "Documentos",
    icon: Lightbulb,
    color: "bg-indigo-50 text-indigo-600",
    url: "https://www.fao.org/agriculture",
  },
  {
    id: "guide-2",
    name: "Manual de Manejo Integrado de Plagas",
    description: "Estrategias de control de plagas sin dependencia de químicos",
    category: "Documentos",
    icon: Lightbulb,
    color: "bg-purple-50 text-purple-600",
    url: "https://www.fao.org/agriculture",
  },
  {
    id: "guide-3",
    name: "Protocolo de Cosecha y Postcosecha",
    description: "Guía técnica para cosecha, secado y almacenamiento de quinua",
    category: "Documentos",
    icon: Lightbulb,
    color: "bg-pink-50 text-pink-600",
    url: "https://www.fao.org/agriculture",
  },
  {
    id: "guide-4",
    name: "Plan de Negocios para Productores",
    description: "Herramienta para planificar y analizar viabilidad económica",
    category: "Documentos",
    icon: TrendingUp,
    color: "bg-rose-50 text-rose-600",
    url: "https://www.fao.org/agriculture",
  },
  {
    id: "seed-storage-1",
    name: "Contenedor de Almacenamiento Hermético",
    description: "Sistema de conservación de semillas con control de humedad",
    category: "Almacenamiento",
    icon: Package,
    color: "bg-gray-100 text-gray-700",
    url: "https://www.fao.org/agriculture",
  },
  {
    id: "processing-1",
    name: "Módulo de Procesamiento Básico",
    description: "Equipo para despepitar y procesar quinua artesanalmente",
    category: "Procesamiento",
    icon: Utensils,
    color: "bg-fuchsia-50 text-fuchsia-600",
    url: "https://www.fao.org/agriculture",
  },
  {
    id: "market-1",
    name: "Certificación Orgánica Internacional",
    description: "Asesoramiento para certificación y acceso a mercados premium",
    category: "Servicios",
    icon: TrendingUp,
    color: "bg-emerald-50 text-emerald-600",
    url: "https://www.fao.org/agriculture",
  },
  {
    id: "training-1",
    name: "Capacitación en Sostenibilidad",
    description: "Cursos de formación en prácticas agroecológicas certificadas",
    category: "Capacitación",
    icon: Lightbulb,
    color: "bg-orange-100 text-orange-700",
    url: "https://www.fao.org/agriculture",
  },
  {
    id: "data-1",
    name: "Base de Datos de Productores",
    description: "Directorio de productores de quinua certificados en la región",
    category: "Información",
    icon: TrendingUp,
    color: "bg-blue-100 text-blue-700",
    url: "https://www.fao.org/agriculture",
  },
  {
    id: "yapu-aroma",
    name: "Yapu Aroma - App Móvil",
    description:
      "Aplicación pensada para el productor: planifica el cultivo, registra costos y acompaña la jornada en el campo, incluso sin conexión a internet.",
    category: "Tecnología",
    icon: Zap,
    color: "bg-primary text-primary-foreground",
    url: "#",
  },
]
